USERPROFILE_DOESNOTEXIST_MESSAGE = 'Email Address is not registered with us'
USERPROFILE_INVALID_LOGIN_INFO_MESSAGE = 'Invalid Username and/or Password Combination'
USERPROFILE_SUCCESSFUL_LOGIN_MESSAGE = 'Welcome Back!'
USERPROFILE_SUCCESSFUL_CREATION_MESSAGE = 'Congrats, Your account has been registered! :)'
REGISTRATION_FORM_INVALID_MESSAGE = 'Please correct the errors below'
LOGIN_FORM_INVALID_MESSAGE = 'Please correct the errors below'